In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

#Load Data

In [2]:
df = pd.read_csv('data/7SegmentDisplay.csv')

In [3]:
df

Digit  Led0  Led1  Led2  Led3  Led4  Led5  Led6
0      0   1.0   1.0   1.0   1.0   1.0   1.0   0.0
1      1   0.0   1.0   1.0   0.0   0.0   0.0   0.0
2      2   1.0   1.0   0.0   1.0   1.0   0.0   1.0
3      3   1.0   1.0   1.0   1.0   0.0   0.0   1.0
4      4   0.0   1.0   1.0   0.0   0.0   1.0   1.0
5      5   1.0   0.0   1.0   1.0   0.0   1.0   1.0
6      6   0.0   0.0   1.0   1.0   1.0   1.0   1.0
7      7   1.0   1.0   1.0   0.0   0.0   0.0   0.0
8      8   1.0   1.0   1.0   1.0   1.0   1.0   1.0
9      9   1.0   1.0   1.0   0.0   0.0   1.0   1.0

#Transform Data

In [4]:
X = df.loc[:, df.columns != 'Digit']
X

Led0  Led1  Led2  Led3  Led4  Led5  Led6
0   1.0   1.0   1.0   1.0   1.0   1.0   0.0
1   0.0   1.0   1.0   0.0   0.0   0.0   0.0
2   1.0   1.0   0.0   1.0   1.0   0.0   1.0
3   1.0   1.0   1.0   1.0   0.0   0.0   1.0
4   0.0   1.0   1.0   0.0   0.0   1.0   1.0
5   1.0   0.0   1.0   1.0   0.0   1.0   1.0
6   0.0   0.0   1.0   1.0   1.0   1.0   1.0
7   1.0   1.0   1.0   0.0   0.0   0.0   0.0
8   1.0   1.0   1.0   1.0   1.0   1.0   1.0
9   1.0   1.0   1.0   0.0   0.0   1.0   1.0

In [5]:
Y = pd.get_dummies(df['Digit'], prefix='Digit')
Y

Digit_0  Digit_1  Digit_2  Digit_3  Digit_4  Digit_5  Digit_6  Digit_7  \
0        1        0        0        0        0        0        0        0   
1        0        1        0        0        0        0        0        0   
2        0        0        1        0        0        0        0        0   
3        0        0        0        1        0        0        0        0   
4        0        0        0        0        1        0        0        0   
5        0        0        0        0        0        1        0        0   
6        0        0        0        0        0        0        1        0   
7        0        0        0        0        0        0        0        1   
8        0        0        0        0        0        0        0        0   
9        0        0        0        0        0        0        0        0   

   Digit_8  Digit_9  
0        0        0  
1        0        0  
2        0        0  
3        0        0  
4        0        0  
5        0        0  
6        0        0  
7        0        0  
8        1        0  
9        0        1

In [6]:
X.shape

(10, 7)

In [7]:
Y.shape

(10, 10)

In [8]:
x_train = np.array(X)

In [9]:
y_train = np.array(Y)

In [10]:
x_train

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  1.,  1.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  1.,  1.,  0.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  0.,  1.,  1.]])

In [11]:
y_train

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8)

#Create Model

In [12]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, Adam

Using TensorFlow backend.


In [13]:
model = Sequential()
model.add(Dense(4, input_shape=(7,), activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(Adam(lr=0.05), 'categorical_crossentropy', metrics=['accuracy'])

#Fit Model

In [14]:
model.fit(x_train, y_train, epochs=500, verbose=1)

Epoch 1/500
10/10 [==============================] - 0s - loss: 2.4381 - acc: 0.2000
Epoch 2/500
10/10 [==============================] - 0s - loss: 2.3119 - acc: 0.1000
Epoch 3/500
10/10 [==============================] - 0s - loss: 2.2380 - acc: 0.2000
Epoch 4/500
10/10 [==============================] - 0s - loss: 2.1670 - acc: 0.2000
Epoch 5/500
10/10 [==============================] - 0s - loss: 2.0979 - acc: 0.3000
Epoch 6/500
10/10 [==============================] - 0s - loss: 2.0250 - acc: 0.3000
Epoch 7/500
10/10 [==============================] - 0s - loss: 1.9543 - acc: 0.4000
Epoch 8/500
10/10 [==============================] - 0s - loss: 1.8901 - acc: 0.4000
Epoch 9/500
10/10 [==============================] - 0s - loss: 1.8213 - acc: 0.4000
Epoch 10/500
10/10 [==============================] - 0s - loss: 1.7556 - acc: 0.4000
Epoch 11/500
10/10 [==============================] - 0s - loss: 1.7022 - acc: 0.4000
Epoch 12/500
10/10 [==============================] - 0s - loss

10/10 [==============================] - 0s - loss: 0.0226 - acc: 1.0000
Epoch 97/500
10/10 [==============================] - 0s - loss: 0.0219 - acc: 1.0000
Epoch 98/500
10/10 [==============================] - 0s - loss: 0.0212 - acc: 1.0000
Epoch 99/500
10/10 [==============================] - 0s - loss: 0.0206 - acc: 1.0000
Epoch 100/500
10/10 [==============================] - 0s - loss: 0.0200 - acc: 1.0000
Epoch 101/500
10/10 [==============================] - 0s - loss: 0.0194 - acc: 1.0000
Epoch 102/500
10/10 [==============================] - 0s - loss: 0.0189 - acc: 1.0000
Epoch 103/500
10/10 [==============================] - 0s - loss: 0.0184 - acc: 1.0000
Epoch 104/500
10/10 [==============================] - 0s - loss: 0.0179 - acc: 1.0000
Epoch 105/500
10/10 [==============================] - 0s - loss: 0.0174 - acc: 1.0000
Epoch 106/500
10/10 [==============================] - 0s - loss: 0.0170 - acc: 1.0000
Epoch 107/500
10/10 [==============================] - 0s - 

10/10 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 191/500
10/10 [==============================] - 0s - loss: 0.0054 - acc: 1.0000
Epoch 192/500
10/10 [==============================] - 0s - loss: 0.0053 - acc: 1.0000
Epoch 193/500
10/10 [==============================] - 0s - loss: 0.0053 - acc: 1.0000
Epoch 194/500
10/10 [==============================] - 0s - loss: 0.0052 - acc: 1.0000
Epoch 195/500
10/10 [==============================] - 0s - loss: 0.0052 - acc: 1.0000
Epoch 196/500
10/10 [==============================] - 0s - loss: 0.0051 - acc: 1.0000
Epoch 197/500
10/10 [==============================] - 0s - loss: 0.0051 - acc: 1.0000
Epoch 198/500
10/10 [==============================] - 0s - loss: 0.0051 - acc: 1.0000
Epoch 199/500
10/10 [==============================] - 0s - loss: 0.0050 - acc: 1.0000
Epoch 200/500
10/10 [==============================] - 0s - loss: 0.0050 - acc: 1.0000
Epoch 201/500
10/10 [==============================] - 0s

10/10 [==============================] - 0s - loss: 0.0028 - acc: 1.0000
Epoch 285/500
10/10 [==============================] - 0s - loss: 0.0028 - acc: 1.0000
Epoch 286/500
10/10 [==============================] - 0s - loss: 0.0027 - acc: 1.0000
Epoch 287/500
10/10 [==============================] - 0s - loss: 0.0027 - acc: 1.0000
Epoch 288/500
10/10 [==============================] - 0s - loss: 0.0027 - acc: 1.0000
Epoch 289/500
10/10 [==============================] - 0s - loss: 0.0027 - acc: 1.0000
Epoch 290/500
10/10 [==============================] - 0s - loss: 0.0027 - acc: 1.0000
Epoch 291/500
10/10 [==============================] - 0s - loss: 0.0027 - acc: 1.0000
Epoch 292/500
10/10 [==============================] - 0s - loss: 0.0027 - acc: 1.0000
Epoch 293/500
10/10 [==============================] - 0s - loss: 0.0026 - acc: 1.0000
Epoch 294/500
10/10 [==============================] - 0s - loss: 0.0026 - acc: 1.0000
Epoch 295/500
10/10 [==============================] - 0s

10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 379/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 380/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 381/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 382/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 383/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 384/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 385/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 386/500
10/10 [==============================] - 0s - loss: 0.0017 - acc: 1.0000
Epoch 387/500
10/10 [==============================] - 0s - loss: 0.0016 - acc: 1.0000
Epoch 388/500
10/10 [==============================] - 0s - loss: 0.0016 - acc: 1.0000
Epoch 389/500
10/10 [==============================] - 0s

10/10 [==============================] - 0s - loss: 0.0012 - acc: 1.0000
Epoch 473/500
10/10 [==============================] - 0s - loss: 0.0012 - acc: 1.0000
Epoch 474/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 475/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 476/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 477/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 478/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 479/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 480/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 481/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 482/500
10/10 [==============================] - 0s - loss: 0.0011 - acc: 1.0000
Epoch 483/500
10/10 [==============================] - 0s

#Model Prediction Test

In [30]:
x_test = np.array([[ 1.,  1.,  1.,  1.,  1.,  1.,  0.]])

In [31]:
y = model.predict(x_test)

In [32]:
y

array([[  9.99527454e-01,   6.52798093e-10,   8.51302684e-05,
          6.91966559e-17,   6.20171484e-11,   4.78068740e-09,
          2.05408451e-05,   5.08574133e-18,   3.66883265e-04,
          3.14850021e-17]], dtype=float32)

#Save Model

In [34]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 4)                 32        
_________________________________________________________________
dense_2 (Dense)              (None, 10)                50        
Total params: 82
Trainable params: 82
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.save('7SegmentDisplay_model.h5')

#Export CoreML Model

In [37]:
from keras.models import load_model  
model = load_model('7SegmentDisplay_model.h5')

In [38]:
import coremltools

In [39]:
coreml_model = coremltools.converters.keras.convert(model, input_names="leds", output_names="digits")

0 : dense_1_input, <keras.engine.topology.InputLayer object at 0x11f48a550>
1 : dense_1, <keras.layers.core.Dense object at 0x11f48a590>
2 : dense_1__activation__, <keras.layers.core.Activation object at 0x12025d0d0>
3 : dense_2, <keras.layers.core.Dense object at 0x11f4cd890>
4 : dense_2__activation__, <keras.layers.core.Activation object at 0x12025d150>


In [40]:
coreml_model.save('7SegmentDisplay_model.mlmodel')

In [41]:
coreml_model

input {
  name: "leds"
  type {
    multiArrayType {
      shape: 7
      dataType: DOUBLE
    }
  }
}
output {
  name: "digits"
  type {
    multiArrayType {
      shape: 10
      dataType: DOUBLE
    }
  }
}

In [42]:
coreml_model.predict({'leds' : [1.,  1.,  1.,  1.,  1.,  1.,  0.]})

{u'digits': array([  9.99527574e-01,   6.52798204e-10,   8.51304358e-05,
          6.91966626e-17,   6.20172663e-11,   4.78069717e-09,
          2.05408851e-05,   5.08574174e-18,   3.66884051e-04,
          3.14851245e-17])}